### ISSUE TITLE
Tests failing, most returning AttributeError: 'NoneType' object has no attribute 'CreateCodec'

### ISSUE THREAD

**Issue by shortbrownman** [anibali/pybraw#1]
I've successfully built and tested this package previously on my local environment consisting of WSL2 Ubuntu. I'm trying to deploy it to an Ubuntu VM in the cloud. I have followed the instructions again but am now unable to run the tests successfully on this VM. Most of the errors returned are AttributeError: 'NoneType' object has no attribute 'CreateCodec' which leads me to think that there's something in my VM's environment that's missing and pybraw isn't able to properly use libBlackmagicRawAPI.so.

Do you have any suggestions?

Also, thanks for putting this package together!

**Comment by anibali** [comment]
I just set up everything from scratch on Ubuntu 21.10 and the tests pass just fine. I did have some library compatibility issues between the Conda environment and the host, but I solved those by setting up the build tools inside the Conda environment rather than on the host (see https://github.com/anibali/pybraw/commit/a87e9bd9dcc5f45572e32e456d3380b214240825). I don't think that this is your issue though.

Based on your observations it sounds like the call to `CreateBlackmagicRawFactoryInstance()` is failing, which probably means that `libBlackmagicRawAPI.so` can't be found at runtime. I can't really help much beyond this I'm afraid.

**Comment by shortbrownman** [comment]
I did try copying the `libBlackmagicRawAPI.so` file into the environment lib rather than `/usr/lib/` before posting the issue. Removing the file altogether fails the testing on the first test and does not continue the testing suite.

I'll try Ubuntu 21.10 to see if I can get it to work that way. Thanks for taking the time to respond.

**Comment by shortbrownman** [comment]
I just wanted to update and let you know I got it working on my server. I had the CPU virtualization configured incorrectly in my VM and also needed to install libgl1 to get things operable. I'm up and running. Thanks again for putting this package together!
